const prodacts = [
        {id:1,
             img: '<img src="./img/catalog_img/catalog/sets/s-dnyom-rojdeniya-3.png" alt="macarron">',
             name: 'Набір макарон "День народження"',
             text: '16 штук в уапковці. Смаки: фісташка, вишня, кокос, шоколад',
             cost: '1300',
             summCost: '1300',
             number: '1'},
        {id:2,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-6.png" alt="macarron">',
            name: '15 макарон у прозорій упаковці',
            text: '15 штук в упаковці. Смаки: фісташка, шоколад-апельсин, полуниця-базилик, ерл-грей, малина, трюфель.',
            cost: '900',
            summCost: '900',
            number: '1'},
        {id:3,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-5.png" alt="macarron">',
            name: 'Набір макарон у закритій упаковці на 6 штук',
            text: '6 штук в упаковці. Смаки: шоколад-банан, лимон, эрл-грей, облипіха-розмарин, малина, лаванда.',
            cost: '350',
            summCost: '350',
            number: '1'},
        {id:4,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-2.png" alt="macarron">',
            name: 'Набір макарон в закрытой коробке на 24 штуки',
            text: '24 штуки в коробке. смаки: лимон, шоколад-банан, фісташка, шоколад-апельсин, обліпиха-розмарин, полуниця-базилік, смородина, кокос, манго-маракуйя, лаванда, ерл-грей, малина.',
            cost: '1400',
            summCost: '1400',
            number: '1'},
        {id:5,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-6.png" alt="macarron">',
            name: 'Набір макарон в прозорій упаковці Натхнення',
            text: '7 штук в упаковці. Смвки: лимон, шоколад-банан, фісташка, шоколад-апельсин, обліпиха-розмарин, полуниця-базилік, смородина.',
            cost: '420',
            summCost: '420',
            number: '1'},
        {id:6,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-1.png" alt="macarron">',
            name: 'Набір макарон в прозорій упаковці Чудова 7',
            text: '7 штук в упаковці. Смаки: фісташка, лаванда, шоколад-банан, манго-маракуйя, полуниця-базилік, малина, смородина.',
            cost: '420',
            summCost: '420',
            number: '1'},
        {id:7,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-2.png" alt="macarron">',
            name: 'Набір макарон в прозорій упаковці Ласунка',
            text: '5 штук в упаковці. Смаки: лимон, шоколад-банан, манго-маракуйя, полуниця-базилік, смородина.',
            cost: '320',
            summCost: '320',
            number: '1'},
        {id:8,
            img: '<img src="./img/catalog_img/catalog/sets/macarons.png" alt="macarron">',
            name: 'Набір макарон в прозорій упаковці Естет',
            text: '5 штук в коробке. Смаки: ерл-грей, блакитнй сир, трюфель, лаванда, кокос.',
            cost: '320',
            summCost: '320',
            number: '1'},
        {id:9,
            img: '<img src="./img/catalog_img/catalog/sets/new-year.png" alt="macarron">',
            name: 'Набір макарон до Нового року',
            text: '16 штук в упаковці. Смаки: фісташка, вишня, шоколад, кокос',
            cost: '1300',
            summCost: '1300',
            number: '1'},
        {id:10,
            img: '<img src="./img/catalog_img/catalog/sets/new-year-2.png" alt="macarron">',
            name: 'Макарони у міні наборі New Year',
            text: '9 штук в упаковці. Смаки: фісташка, вишня, шоколад',
            cost: '750',
            summCost: '750',
            number: '1'},
        {id:11,
            img: '<img src="./img/catalog_img/catalog/sets/new-year-4.png" alt="macarron">',
            name: 'Макарони у міні наборі до Нового року',
            text: '9 штук в упаковці. Смаки: фісташка, вишня, шоколад',
            cost: '750',
            summCost: '750',
            number: '1'},
        {id:12,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-3.png" alt="macarron">',
            name: 'Макарони у міні наборі до дня весілля',
            text: '9 штук в упаковці. Смаки: фісташка, вишня, шоколад',
            cost: '750',
            summCost: '750',
            number: '1'},
        {id:13,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-13.png" alt="macarron">',
            name: 'Макарони у вигляді бонбоньєрки на весілля',
            text: '3 макаронс в наборі. Смаки на вибір',
            cost: '240',
            summCost: '240',
            number: '1'},
        {id:14,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-9.png" alt="macarron">',
            name: 'Макарони у вигляді бонбоньєрки з іменами гостей',
            text: 'Смаки на вибір',
            cost: '85', 
            summCost: '85', 
            number: '1'},
        {id:15,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-18.png" alt="macarron">',
            name: 'Макарони у вигляді бонбоньєрки для гостей',
            text: '2 макарони в упаковці. Смаки на вибір',
            cost: '200',
            summCost: '200',
            number: '1'},
        {id:16,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-14.png" alt="macarron">',
            name: 'Пирамідка из макаронс, 14 поверхів',
            text: '350 макаронс в наборі. Смаки: фісташка, полуниця-базилік, кокос, пармезан, чорний трюфель, солона карамель, снікерс, вишня, шоколад-банан, блакитний сир, ананас, облипіха-розмарин, малина, ерл-грей, лаванда, песто, смородина, манго-маракуйя',
            cost: '2100',
            summCost: '2100',
            number: '1'},
        {id:17,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-16.png" alt="macarron">',
            name: 'Пірамідка із макарон, 10 поверхів',
            text: '240 макарон в наборі. Смаки: фісташка, полуниця-базилік, кокос, пармезан, чорний трюфель, солона карамель, снікерс, вишня, шоколад-банан, блакитний сір, ананас, облепіха-розмарин',
            cost: '1400',
            summCost: '1400',
            number: '1'},
        {id:18,
            img: '<img src="./img/catalog_img/catalog/sets/uchitel-5.png" alt="macarron">',
            name: 'Набір-міні до дня вихователя',
            text: '9 штук в коробці. Смаки: фісташка, вишня, шоколад',
            cost: '750',
            prisummCostce: '750',
            number: '1'},
            //--------------ecler********************************************************************
        {id:19,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-7.png" alt="ekler">',
            name: 'Ванільний еклер',
            text: 'надзвичайно смачні еклери виготовлені тільки із натуральних інгредієнтів, без хімії та консервантів!',
            cost: '99',
            summCost: '99',
            number: '1'},
        {id:20,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-13.png" alt="ekler">',
            name: 'Полуничний еклер',
            text: 'Надзвичайно смачні еклери виготовлені тільки із натуральних інгредієнтів, без хімії та консервантів!',
            cost: '99',
            summCost: '99',
            number: '1'},
        {id:21,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-10.png" alt="ekler">',
            name: 'Малиновий еклер',
            text: 'Надзвичайно смачні еклери виготовлені тільки із натуральних інгредієнтів, без хімії та консервантів!',
            cost: '99',
            summCost: '99',
            number: '1'},
        {id:22,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-1.png" alt="ekler">',
            name: 'Шоколадний еклер',
            text: 'Надзвичайно смачні еклери виготовлені тільки із натуральних інгредієнтів, без хімії та консервантів!',
            cost: '99',
            summCost: '99',
            number: '1'},
        {id:23,
            img: '<img src="./img/catalog_img/catalog/ecler/ekler.png" alt="ekler">',
            name: 'Еклер з карамеллю',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',
            summCost: '99',
            number: '1'},
        {id:24,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-17.png" alt="ekler">',
            name: 'Набір з 6 еклерів',
            text: '6 смаків у наборі: ванільний, смородиновий, полуничний, малиновий, карамельний, шоколадний',
            cost: '600',
            summCost: '600',
            number: '1'},
        // ************************************************************************************
    {id:25,
            img: '<img src="./img/catalog_img/catalog/vafle_pipes/trubochki-4.png" alt="trubochki">',
            name: 'Набір трубочек зі згущенним молоком',
            text: 'У складі наших вафель — натуральне масло та яйця. Ми не використовуємо яєчний жовток та сухі порошки, не використовуємо консерванти, розпушувачі та загусники. У складі начинки: натуральне сгущене молоко, масло та молоко',
            cost: '900',
            summCost: '900',
            number: '1'},
    {id:26,
            img: '<img src="./img/catalog_img/catalog/vafle_pipes/trubochki-3.png" alt="trubochki">',
            name: 'Трубочка зі згущенним молоком',
            text: 'У складі наших вафель — натуральне масло та яйця. Ми не використовуємо яєчний жовток та сухі порошки, не використовуємо консерванти, розпушувачі та загусники. У складі начинки: натуральне сгущене молоко, масло та молоко',
            cost: '95',
            summCost: '95',
            number: '1'},
    //**********************************************************************************************
    {id:27,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli_macaronshop.png" alt="profitroli">',
            name: 'BIG-профітролі',
            text: '40 штук в упаковці. Смаки: абрикос, карамель, шоколад, малина, крем-брюле',
            cost: '2000',
            summCost: '2000',
            number: '1'},
    {id:28,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli_kupit.png" alt="profitroli">',
            name: 'Чудові «15»',
            text: '15 штук в упаковці. Смаки: абрикос, малина, крем-брюле, шоколад, карамель',
            cost: '450',
            summCost: '450',
            number: '1'},
    {id:29,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli-4.png" alt="profitroli">',
            name: 'Профітролі міні з малиною',
            text: '9 штук в упаковці. Смаки: малина, карамель',
            cost: '330',
            summCost: '330',
            number: '1'},
    {id:30,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitrili-mini.png" alt="profitroli">',
            name: 'Профітролі міні с шоколадом',
            text: '9 штук в упаковці. Смаки: шоколад, карамель',
            cost: '330',
            summCost: '330',
            number: '1'},           
]